name: Building on CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Initializing Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libhandy-0.0-dev

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Cloning gtkcord
      uses: actions/checkout@v2

    - name: Get Go dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .
